---
language: java

addons:
  sonarcloud:
    organization: "anath"
    token:
      secure: tZWPobcg+n+vpwKrTD4ztfat4CNynqE/mQcFx9SLpYsZVdXHYP6qt46hKud+WtDBFN27VmflnBVgyTJJUbtFUOO2M/prFLyeV7n6uE8bGIkrjSUzXXy1Eh5uVmMkhgC1roOjQLEpYkBg4Cj0M88taIxGtZbKae3p5O8GVw6OI8qtsAG3Twj1YrbWCltiH3RW8Jj8W1JFooL9ho8aNrvqOtDosTa4SW/utuHsNUXhy0GCMaqunm9s4017Cf3s/8dFO74RR+nUlZYQxy/zYOtksab6wN0mvlienJSkXXAdIovgTWE07l35mqj6wRgrolvOtBuJtBI/NGkn6PsE3KfVudkzlFKg+3DTOpbmsfmRHGl8bN8aezR8DczlrrHH3seZkeur8UXVDAN4UNFK1NagxO13Ctbwa7BL+zQegGSk6uRkMglsN++aSi7N3X1fnWcQG3eXxpXdRLq5v5uw7j52g+PratBXB3p/zCpQUqCE8o3ndmClklKyAPAtO/fL3CVTIhBEmLbUnG8Sa+Zou4x0wP1PMbI8A8hT/6kzddm26AYUPxnb5GgdFid7M3ibBLozKk/zcAxo7GLNTwlPjJ/XeN0EBfc4joOGCzh4DYqj1mLVjHda5WtzP6jJIwX+7sIfjhGQnOM0dr8FKwc4NrP8vRkGNl1IZ6pHNXuVhvumtok=

script:
 - mvn verify -B
 - mvn sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
