sudo: required
language: java
services:
- docker
addons:
  sonarcloud:
    organization: anath
    token:
      secure: KYQSPp/O4nL3TzN9qpooNfcamHfIlb59oV6EHryMSr6zjoYa4CtcHGEOw2YSshxxdRa5pmYxf4RM59LHCQcvSzuZE+DSxCkn931Zy5YNIjsTgPVypIg2rUmmk1C4LBoEzLqBgBUuTSo0+p8H3Mf3YnCTKO2NEwAXibv1co4oFS6RBdmx6NYSvpTI54yj35Ej+iVFW9JYVTvbnEplpeEM/UNo5pXoNHJXsfQ1aykVLsW+wo9tPWa5YIjh/mWFC5e2ADHvxZKPT+oZhnjXN7g5NLV4gH5d3A6uLi/nEAsrCWgPyMFmbp70DUjZws6Xgt6XtKmYlRZIlsS60wMPXlTnnVTTb2/boTnnHLcMMLvrglE91g+CMs+1rLpV/ToKmEM3qLS2zPfW0DElxdMe1WfL4y9aeOjkuTsa5a7N3arhd25VeSksZGa0FOVrM1B+DDVicgd1ig75FZus0fAeQ/pTzi5NbUicMy6C+kbxmgdypSrMKizIhMet6Wx93+qEUTVvXRiQp1rJ8u5x1b8kHKmMGyXnfPMDUAHU4BbTpZzCDysdMzGuzvA4+o5H3MqPYOt6ZjwJe3DOmp/6cZpy8fgq11m9R2vHN1YO++yjPA4m4jfhk44HHutH68NOYlddt0EKNujL3xydXQxtWoSsYn79ST7egd5/8ROisBAWLlLqXfY=
script:
- mvn package -B

deploy:
  provider: script
  script: bash docker/docker_build_dev.sh
  on:
    branch: travis_docker_build

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
env:
  global:
  - secure: MBZ33QOTb/Rw4h/HhKn5PQh4RCgtkdj9xlWmFZtDkDWZC9e9xUxPtzel1hm74TZTKyDSgcQtjBPZZzjyzesdHHX9vOmifPn0rANXrCIhL3+hCimQeCVgpaYQ+9/0dUblaTU9Q5Mg+1MOOdg2GAJcj6k13ixyD0bhhcl/fNQqeg8tcFeaczD++L08TU3L3wm0ayS9W7/FMQBc47kG3ATpLfsp82srxh1D9M2+hNQOV7NiBfThV8FCs1qq/mhVePRY5IxLiA+FyNPkyz3FwiDKyl6U27MomElqHrd6xNRxTT7MXTgGwIl6YAjQEVAlGPj7O84gi6UwTrBdn8EWILCZL70FoKM0PUI9mzhgEb5c4mxOBizeN3jRFMeQ0snbPYFSZJqaNKSNAZx4Gb/Wd/hYc9oYozY+/HlG8cwekKrbGChqVuYVpzczr/ICKJjDjN1pYAqgnX3YWPjscV1/q0TXCzcMHcLjx7V5n+LwkyAC6E0WxQiBuNnQn0i/SEysIayrXYi1U5OzoTJwRHYTi066FojvV+q1xLG2YJio5BxwPKX/GJG2DdQ7AAPTTCy0MLojOYCRD/tsqcSMQxFG3Fkf9Ye/mkyEv8x/9X9XGnA48Qzq3cUu987otYCY94fg8btt8LVznfV42hxFb1UyB/xIskgLuzHcY2pa9HoS29k3ymQ=
  # Docker hub user
  - secure: HI0PBn2Pht4ciBGr5E3mrrMeaFvrBSWDbeHPj1BSLNOkZtFohgG/s3ULsRk40d0laas4o5jgMxoOnUe7zFwV/1lQFtN/acJ7MxlG6caJ9E/7jAvRHC7zsMIl9iZONpnEZPQIft5PgA91gpGjHorXCbze3ozgRPgId7wuFj1dBDvFElg/EinBGZLaceD8ZC8sqJxS3a7TI8LMIDVQ+mAqGCCDMQViIQFvz7WIqEOpmAAa8GomNFYiyqfqli/EnS4Nzulr5uwhVx0mkh/YS/VcOaldbvftqNOtOqMdYMWEJp/zXJNybtN4gLfIK7WsL/a+r/nb8njCcnoEdYO5eFGMfWsDuCo9WzYWGAS4NxrPrL+dZu++0MW2uCWXeypCnVT49mToggEVW0KYT6ftlEw3BaVeQl3oNms1qY6kDiCRf/qkzDqAZ8L0Tqe4WPfY5eYwhPoAgosKm2ZglcawJPT2fNJQ5tk5+HZtl8ttAnrJFNPub4ygQDkU6R+ZhFuONMQdYIw8gZXIWFvpwc+hwWNOpe6SVxzDD4dvFANJ+pzAiCHfiTTTGdfeZT6AxQm8HABuNqxcQFW2nv0EAO5tkd5Io3m+ZTG21E2xnVn1B6/ykXp/vuuoPFEQDri6IUAu3czFEEm+6S85v+nBQoyaB+PV1jdLuxsZlNpROFmN9EuLgok=
