sudo: required
language: java
services:
- docker
addons:
  sonarcloud:
    organization: anath
    token:
      secure: KYQSPp/O4nL3TzN9qpooNfcamHfIlb59oV6EHryMSr6zjoYa4CtcHGEOw2YSshxxdRa5pmYxf4RM59LHCQcvSzuZE+DSxCkn931Zy5YNIjsTgPVypIg2rUmmk1C4LBoEzLqBgBUuTSo0+p8H3Mf3YnCTKO2NEwAXibv1co4oFS6RBdmx6NYSvpTI54yj35Ej+iVFW9JYVTvbnEplpeEM/UNo5pXoNHJXsfQ1aykVLsW+wo9tPWa5YIjh/mWFC5e2ADHvxZKPT+oZhnjXN7g5NLV4gH5d3A6uLi/nEAsrCWgPyMFmbp70DUjZws6Xgt6XtKmYlRZIlsS60wMPXlTnnVTTb2/boTnnHLcMMLvrglE91g+CMs+1rLpV/ToKmEM3qLS2zPfW0DElxdMe1WfL4y9aeOjkuTsa5a7N3arhd25VeSksZGa0FOVrM1B+DDVicgd1ig75FZus0fAeQ/pTzi5NbUicMy6C+kbxmgdypSrMKizIhMet6Wx93+qEUTVvXRiQp1rJ8u5x1b8kHKmMGyXnfPMDUAHU4BbTpZzCDysdMzGuzvA4+o5H3MqPYOt6ZjwJe3DOmp/6cZpy8fgq11m9R2vHN1YO++yjPA4m4jfhk44HHutH68NOYlddt0EKNujL3xydXQxtWoSsYn79ST7egd5/8ROisBAWLlLqXfY=
script:
- mvn package -B

deploy:
  provider: script
  script: bash docker/docker_build_dev.sh
  on:
    branch: travis_docker_build

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
env:
  global:
  - secure: nKhmmPoYU4W2Y4cyVwDVdAGL/2nvrmpmqTvTEgyrGdPCuaFSVV6iFVPjzv66uBIKX9wV6eQZnNj2gd6vX+TR7lSpLSMTidP90mnp01aNS0uacfZ5oO/JqTBweS4PapgyQWEKtHM+7L5dGzNxQp+gfCSuflt1fzih697+Krk/29l+3ZQqOY8uShCF7ID+H1Teu/ODW46LGkdZhRtxqKhmFaXpfkb0D91Usrlb8NMIHovTINHCTc0qksJWCoejwp5MrwFFZeCOmGFlCXiMpQhHLBhb85oss8YbG9JCqx4uJMz/entKepyWIZNI4+lDYz2euOdMAij/va++EnbluacX92Q7KkOgMzMVrD8lhutqbZQWn+4eXNo+4XwmdX8iG5j0S+E9kaQr93vl5nxWbl/dXs9yJyDbaR8th3qts/8+toTlZi6rdep3tgQr4Q9kuBWDyQPUhW6aQGAK0b+bCrybTfGtD4hQGTDSNU1Unu/GBdo7gCS16plpxUwNTn29r76UiawoIarivZO8ukAJfNad7P5nUU9f4N4uabn1ojRMr09cbHShxTuYXj6W1kCCHuuEBLqAM/icvNCxJJHBWcpBMPayNBTdIVjy7nqCHZMra8zenhL3bDSBz9iaVarJSmy+vYrSK/xR9g0bID4XbXxFD8h2vnEuHVHtL9u+nuNPMhQ=
  # Docker hub user
  - secure: VtMaDFRiJSLzT9L9cSSai+WFEzVJio8RfuCCu6I16XlTFxxTr0TZ7wtF/oqAMlIgE67C1P9dXnxSO+/M6X51TM4H+5XQnd46m0+wNc26i1fi1L50FXL2sFbbkx/UoRXH8QNoQeOFxC9UpF+XtXHlhGAnIsPE444w61y0RQfDqkL4wbvJPkXoCgfox92he2JQTBTmjUfEkjbpA1koRz7i5VSMJFjyXDQ5X4aClLhs/WUS5GdBtJ6RZtOTBGhVN2SjVwoUeVkVaiHXZ8fIAd5ZA66IgiY29s6dJMZZ+ZAGMYpxyvqtaXRSK/cjsqxsI87IjpZ+oxtNgFaf8MtTWWB2lvVv6maW3GnF3/CSGl3v/0Ifiwdq0sYLKSI82NZAtsxbnXzLy2n9vDHWj+xBKQ0ChtFYTupQ+iViirXTZ7kKPTtSrWjunnng034Bpqo/mqgoaDFhY5GDF6WpCtqpDAZ/uWxw91jGfPC5clddoCvWV9wKnh5uxHUxpdf1wk0BP3YlZphezAjiPFWUt2U8CCIkj5RK8AqRZrYW0L/P+H3EOlB4teFvfBeipQ3CQuiYZBJE1yubALWSgMzWaW6r+sq4kIAH5BouX3TelbY9jJzuBtK4PZjrNKezXQuhuWoLeUDVDjOS57s3gQ+kA5Cpkn7T8tlP5LicWFszxbR/JgkL334=
