sudo: required
language: java
services:
- docker
addons:
  sonarcloud:
    organization: anath
    token:
      secure: KYQSPp/O4nL3TzN9qpooNfcamHfIlb59oV6EHryMSr6zjoYa4CtcHGEOw2YSshxxdRa5pmYxf4RM59LHCQcvSzuZE+DSxCkn931Zy5YNIjsTgPVypIg2rUmmk1C4LBoEzLqBgBUuTSo0+p8H3Mf3YnCTKO2NEwAXibv1co4oFS6RBdmx6NYSvpTI54yj35Ej+iVFW9JYVTvbnEplpeEM/UNo5pXoNHJXsfQ1aykVLsW+wo9tPWa5YIjh/mWFC5e2ADHvxZKPT+oZhnjXN7g5NLV4gH5d3A6uLi/nEAsrCWgPyMFmbp70DUjZws6Xgt6XtKmYlRZIlsS60wMPXlTnnVTTb2/boTnnHLcMMLvrglE91g+CMs+1rLpV/ToKmEM3qLS2zPfW0DElxdMe1WfL4y9aeOjkuTsa5a7N3arhd25VeSksZGa0FOVrM1B+DDVicgd1ig75FZus0fAeQ/pTzi5NbUicMy6C+kbxmgdypSrMKizIhMet6Wx93+qEUTVvXRiQp1rJ8u5x1b8kHKmMGyXnfPMDUAHU4BbTpZzCDysdMzGuzvA4+o5H3MqPYOt6ZjwJe3DOmp/6cZpy8fgq11m9R2vHN1YO++yjPA4m4jfhk44HHutH68NOYlddt0EKNujL3xydXQxtWoSsYn79ST7egd5/8ROisBAWLlLqXfY=
script:
- mvn package -B

deploy:
  provider: script
  script: bash docker/docker_build_dev.sh
  on:
    branch: travis_docker_build

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
env:
  global:
  - secure: W55B5rEMT3aFqCSbciSVtd/t0ORMbmVamoqHCQseEqmKA4fLfV/mxX8e7i+NgrNBqQ+YY0FcvM3L9DIviZkk5V4yQcePRRNo70SNiYITaFMmax+Lu5c2pfUO5l0pNponRUqREzM97tU7oOnRimRw0kEXYjplVDDhCY6e/apa1ZobIbw6iP1iMCI2XaCidrh0O+NU8M3RNjRpwZN/CfiwB/QN0FWn9Ex8eqjrcvM8o3kVIMSyh10eguXFEW+k2XXyQCp8Dp4Ikx/ydzcH7FYP8XeYnAVieSs6bJKHvLWYEhogv1BJLsArWAipEli7bXnQLjEs6+4MAnhE1TjUNdz9FQxFYJ5yn7Pbten4jpzjYo9xwxanYE1BN3XSMk7Xn4cmKBhBqHUYSdbsT3/4fbz0eqlR3trhYxzN34GtSC5DmTk2ZX3h9WpU1OC+/YnYBS5Bo7cPTQnpuUJCkn4IJpoqn6gnDxApmzuKZkzsv07JJckA6NLcnFnXjde0rCE1vbYzebgDk80NiXWKGySBnDsLKmNOaufzgaCZXGTgQgIxdE6C+NAJ9bRJLartcjYU6SldCvIqxSFwXcMt4Tja7y+E13dazxtM0M+qxIPvnxEyEBpRTrcAYYNdW2fZIG9XsCNlpiVOZN9uUiYOx+eb9kaPV+vtIkmozXGzSQotS7ra+2Y=
  # Docker hub user
  - secure: VtMaDFRiJSLzT9L9cSSai+WFEzVJio8RfuCCu6I16XlTFxxTr0TZ7wtF/oqAMlIgE67C1P9dXnxSO+/M6X51TM4H+5XQnd46m0+wNc26i1fi1L50FXL2sFbbkx/UoRXH8QNoQeOFxC9UpF+XtXHlhGAnIsPE444w61y0RQfDqkL4wbvJPkXoCgfox92he2JQTBTmjUfEkjbpA1koRz7i5VSMJFjyXDQ5X4aClLhs/WUS5GdBtJ6RZtOTBGhVN2SjVwoUeVkVaiHXZ8fIAd5ZA66IgiY29s6dJMZZ+ZAGMYpxyvqtaXRSK/cjsqxsI87IjpZ+oxtNgFaf8MtTWWB2lvVv6maW3GnF3/CSGl3v/0Ifiwdq0sYLKSI82NZAtsxbnXzLy2n9vDHWj+xBKQ0ChtFYTupQ+iViirXTZ7kKPTtSrWjunnng034Bpqo/mqgoaDFhY5GDF6WpCtqpDAZ/uWxw91jGfPC5clddoCvWV9wKnh5uxHUxpdf1wk0BP3YlZphezAjiPFWUt2U8CCIkj5RK8AqRZrYW0L/P+H3EOlB4teFvfBeipQ3CQuiYZBJE1yubALWSgMzWaW6r+sq4kIAH5BouX3TelbY9jJzuBtK4PZjrNKezXQuhuWoLeUDVDjOS57s3gQ+kA5Cpkn7T8tlP5LicWFszxbR/JgkL334=
