sudo: required
language: java

services:
  - docker

addons:
  sonarcloud:
    organization: anath
    token:
      secure: KYQSPp/O4nL3TzN9qpooNfcamHfIlb59oV6EHryMSr6zjoYa4CtcHGEOw2YSshxxdRa5pmYxf4RM59LHCQcvSzuZE+DSxCkn931Zy5YNIjsTgPVypIg2rUmmk1C4LBoEzLqBgBUuTSo0+p8H3Mf3YnCTKO2NEwAXibv1co4oFS6RBdmx6NYSvpTI54yj35Ej+iVFW9JYVTvbnEplpeEM/UNo5pXoNHJXsfQ1aykVLsW+wo9tPWa5YIjh/mWFC5e2ADHvxZKPT+oZhnjXN7g5NLV4gH5d3A6uLi/nEAsrCWgPyMFmbp70DUjZws6Xgt6XtKmYlRZIlsS60wMPXlTnnVTTb2/boTnnHLcMMLvrglE91g+CMs+1rLpV/ToKmEM3qLS2zPfW0DElxdMe1WfL4y9aeOjkuTsa5a7N3arhd25VeSksZGa0FOVrM1B+DDVicgd1ig75FZus0fAeQ/pTzi5NbUicMy6C+kbxmgdypSrMKizIhMet6Wx93+qEUTVvXRiQp1rJ8u5x1b8kHKmMGyXnfPMDUAHU4BbTpZzCDysdMzGuzvA4+o5H3MqPYOt6ZjwJe3DOmp/6cZpy8fgq11m9R2vHN1YO++yjPA4m4jfhk44HHutH68NOYlddt0EKNujL3xydXQxtWoSsYn79ST7egd5/8ROisBAWLlLqXfY=

script:
- mvn package -B

deploy:
  provider: script
  script: bash docker_build_dev.sh
  on:
    branch: travis_docker_build

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

env:
  global:
  - secure: YYn7jtb2Ed13P4HaQSzWhTr6uQhE4I6O2JxA+svuChiOF6gDEuyjf5R6IFd2G1sqzeR8BW8ldSgpphUuzwHIn+fT48MC0Z9sA1S6AWawr3gtZhrRf2r1IVEkoAXf8X2rQpRen4B7dAu6C0KUZZOgbZjL3YtMoF6JJaIMDpib/whfJa41m4naDgh4m4oGY5/H11Nmk0ZZjsTboFnz91W6hr8Fcv+J5WBjXBFBl8J0lyrzGnsw9uyncppDp5+8jGjew/rCJkZmWuK/QK93I2NibqOAFy5bCEi4LZ81V+W/gbOm1YN1WbrKPGOiDDKNT2YNsCGqmIk9jY4CvEdtZ+/8wtOSF95L+G+LswSWpHfxl3Uf1bXNl3bdJc2//9lf9P36qpY4NNlghjHU1mBPj40YOioaJgGk5pbCacUh/uKhqUjOK7jsdPYlodQEYV+Sax4D/8TQ7eeQsXNLwdvjj//T68GE+zR9yw+1orfgOrsoTdqOsEz+GBTLt3qkwE6UP2tXf6bQfWuV6dBzy341sSfa1t1WLqH10PGQVEcWh/5SQ+TPEK0i3PVl7gdJG+R/rMT5BnFoVyyklh34uDoFre5ad62NJwmk6BuhVGUV6DQdOPcPd3qLYZy0Uk5oEArnHlDoTMvp59tF7aCgJnRBsGC3Gdk03TPokiISdaOwFmYZWKo=
  - secure: pRywljTYIuwdmIsMAIcHcH6a9D4DXUweG3q7IqTDSIkKo7siREluiqTuJAuFTX2onhgiY8LGj8qZVQ92JcDno+bzGbgEDR1yd0u2WiZi8NtK8W2AzOa295LKZVitnA6ZOkTmmo1ylDnUOF8v/r2ex28X9j786kjq0ZHlwP4ZFKeM2W9ydxvWqLLSgRkHYzXabgzW1kHZ4qTgCW/vbcBqM8jzC+KOE4XVce51zpOi4fLaEmoaZKwCcq6VmFQj7votCJUdtuc5PFbGrWHZWLtoqYRkxvkkMrmWdKg/EzJ5FYwwJfchvxoosmCAiusKrazFQOFIaCcW9MCklTkJL1LwOUDGmsqXRVsubL8tzrG/ctaUdbayPNuRJz9M81ySOKdIbx7alacei9ljZaxUQQs7t0ICMYzK3uO2dfEb7vkoVoU8aG7PjDrY8J7CnSLXt+r44uoRoLZWe1TRdspPofuIdS/CkWKja7Hq+PF2W2uJ9Hb/IJsRwc7UfDhRdDUIWkMtq5ZynuNgEyjXBR2E81xSASegg81vEFrtbptxoabixT0VbtsfFhViA8JskATZwUI5VQur568+bLQl34N+EchGJR2J9IrHTebs27U4B6uvMp8EpMTRwJoMeU5OdV6tq7rvaDkTab34GY1sjisVxdIgiPzPhhY8Qas+fMAVMTqC/Aw=
